const H='https://api.hyperliquid.xyz/info';
const post=async body=>await http.fetch(H,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
const now=Date.now();
const mc=await post({type:'metaAndAssetCtxs'}); const meta=Array.isArray(mc)?mc[0]:{}; const ctxs=Array.isArray(mc)?(mc[1]||[]):[]; const uni=Array.isArray(meta.universe)?meta.universe:[];
const markets=uni.map((u,i)=>{const c=ctxs[i]||{};return {coin:u.name,mark:Number(c.markPx||0),oracle:Number(c.oraclePx||0),currentFundingHourly:Number(c.funding||0),openInterest:Number(c.openInterest||0),dayVolume:Number(c.dayNtlVlm||0),hip3:String(u.name||'').includes(':')||String(u.name||'').startsWith('@')}}).filter(x=>x.coin);
const spotPairs={};try{const sm=await post({type:'spotMetaAndAssetCtxs'});const su=Array.isArray(sm)?(sm[0]?.universe||[]):[];for(const p of su){const n=String(p.name||'');if(n.includes('/USDC'))spotPairs[n.split('/')[0]]=n}}catch(e){log('spot metadata unavailable')}
const depth=async(coin,ref)=>{try{const b=await post({type:'l2Book',coin});const lv=Array.isArray(b?.levels)?b.levels:[];const all=[...(Array.isArray(lv[0])?lv[0]:[]),...(Array.isArray(lv[1])?lv[1]:[])];const mid=Number(ref||0);let total=0;for(const l of all){const px=Number(l.px),sz=Number(l.sz);if(px>0&&sz>0&&(!mid||Math.abs(px-mid)/mid<=.005))total+=px*sz}return total||0}catch(e){return 0}};
const hist={};for(const m of markets.slice(0,100)){try{const a=await post({type:'fundingHistory',coin:m.coin,startTime:now-30*86400000,endTime:now});const rates=(Array.isArray(a)?a:[]).map(x=>Number(x.fundingRate)).filter(Number.isFinite).slice(-168);const mean=x=>x.length?x.reduce((s,v)=>s+v,0)/x.length:0;const sd=x=>{if(x.length<2)return 0;const z=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-z)**2,0)/x.length)};const pos=x=>x.length?x.filter(v=>v>0).length/x.length:0;let st=[],run=0;for(const v of rates){if(v>0)run++;else if(run){st.push(run);run=0}}if(run)st.push(run);st.sort((a,b)=>a-b);hist[m.coin]={mean7d:mean(rates),positiveShare7d:pos(rates),stdev7d:sd(rates),positiveStreakMedianHours:st.length?st[Math.floor((st.length-1)/2)]:0,samples7d:rates.length}}catch(e){log('history unavailable',m.coin)}}
const ds=await Promise.all(markets.slice(0,50).map(async m=>{const pair=spotPairs[m.coin];return {coin:m.coin,spotPair:pair||'',spotDepthUsd:pair?await depth(pair,m.mark):0,perpDepthUsd:await depth(m.coin,m.mark)}}));const dm=Object.fromEntries(ds.map(x=>[x.coin,x]));let predicted=[];try{const r=await post({type:'predictedFundings'});predicted=Array.isArray(r)?r:[]}catch(e){}let userFunding=[];try{const me=await bankr.wallet.me();const r=await post({type:'userFunding',user:me.evmAddress||me.address});userFunding=Array.isArray(r)?r:[]}catch(e){}
const ann=r=>r*8760*100;const rows=markets.map(m=>{const h=hist[m.coin]||{mean7d:0,positiveShare7d:0,stdev7d:0,positiveStreakMedianHours:0,samples7d:0};const d=dm[m.coin]||{};return {...m,...h,...d,spotAvailable:!!d.spotPair,bookReachable:Boolean(d.perpDepthUsd>0),apr7dAnnualizedPct:ann(h.mean7d),currentAprAnnualizedPct:ann(m.currentFundingHourly),spikeVsMean:Math.abs(h.mean7d)>1e-12?Math.abs(m.currentFundingHourly/h.mean7d):0}});const out={fetchedAt:now,annualization:'hourly funding × 24 × 365; annualized-from-recent-mean, not expected return',fundingCapHourly:.04,markets:rows,predictedFundings:predicted,userFunding:userFunding.slice(-500)};await appKV.set('funding_snapshot',out);await appKV.set('funding_meta',{fetchedAt:now,marketCount:rows.length});return {ok:true,fetchedAt:now,marketCount:rows.length,predictedCount:predicted.length,userFundingCount:userFunding.length,depthCount:ds.length};